package reports

import (
	"bytes"
	"fmt"
	"html/template"
)

// RenderHTML produces a self-contained HTML page with inline CSS so the
// artifact can be emailed, stored in MinIO, or attached to a luận-văn
// appendix without external assets.
func RenderHTML(r *WeeklyReport) (string, error) {
	tmpl, err := template.New("weekly").Funcs(template.FuncMap{
		"mttrHuman": func(seconds float64) string {
			if seconds <= 0 {
				return "n/a"
			}
			m := seconds / 60
			if m < 60 {
				return fmt.Sprintf("%.1f min", m)
			}
			return fmt.Sprintf("%.1f h", m/60)
		},
	}).Parse(weeklyHTML)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := tmpl.Execute(&b, r); err != nil {
		return "", err
	}
	return b.String(), nil
}

const weeklyHTML = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>ZT-SOC weekly report — {{.WeekISO}}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; color: #222; max-width: 820px; margin: 24px auto; padding: 0 16px; }
  h1   { color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 6px; }
  h2   { color: #34495e; margin-top: 28px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
  th, td { padding: 6px 10px; border-bottom: 1px solid #ddd; text-align: left; font-size: 14px; }
  th  { background: #ecf0f1; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .meta { color: #7f8c8d; font-size: 13px; }
  .sev-critical { color: #c0392b; font-weight: 600; }
  .sev-high     { color: #d35400; font-weight: 600; }
  .sev-medium   { color: #2980b9; }
  .sev-low      { color: #7f8c8d; }
</style></head><body>

<h1>ZT-SOC weekly report — {{.WeekISO}}</h1>
<p class="meta">Window: {{.From.Format "2006-01-02 15:04 MST"}} → {{.To.Format "2006-01-02 15:04 MST"}}<br>
Generated: {{.GeneratedAt.Format "2006-01-02 15:04 MST"}}</p>

<h2>Headline</h2>
<table>
  <tr><th>Total incidents</th><td class="num">{{.TotalIncidents}}</td></tr>
  <tr><th>MTTR median (ack)</th><td class="num">{{mttrHuman .MTTRMedianSeconds}}</td></tr>
  <tr><th>Audit events recorded</th><td class="num">{{.AuditEventsCount}}</td></tr>
</table>

<h2>Severity breakdown</h2>
<table>
  <thead><tr><th>Severity</th><th class="num">Count</th></tr></thead>
  <tbody>
    {{range $sev, $n := .BySeverity}}
    <tr><td><span class="sev-{{$sev}}">{{$sev}}</span></td><td class="num">{{$n}}</td></tr>
    {{else}}
    <tr><td colspan="2"><em>No incidents.</em></td></tr>
    {{end}}
  </tbody>
</table>

<h2>Top attackers (by incident count)</h2>
<table>
  <thead><tr><th>Source IP</th><th class="num">Incidents</th></tr></thead>
  <tbody>
    {{range .TopAttackers}}
    <tr><td><code>{{.SourceIP}}</code></td><td class="num">{{.Count}}</td></tr>
    {{else}}
    <tr><td colspan="2"><em>No attackers in window.</em></td></tr>
    {{end}}
  </tbody>
</table>

<h2>Response actions</h2>
<table>
  <thead><tr><th>Action type</th><th class="num">Count</th></tr></thead>
  <tbody>
    {{range $type, $n := .ActionsBreakdown}}
    <tr><td>{{$type}}</td><td class="num">{{$n}}</td></tr>
    {{else}}
    <tr><td colspan="2"><em>No actions issued.</em></td></tr>
    {{end}}
  </tbody>
</table>

<p class="meta">Generated by zt-soc/incident-service.</p>
</body></html>`
