// Package response generates Kubernetes NetworkPolicy YAML for analyst
// review and (when APPLY_MODE=apply) for automated enforcement.
//
// The generated NetworkPolicy denies ALL egress from the offending (attacker)
// Pod, selected by the per-incident label LabelKey(id)=true that the enforcer
// patches onto that Pod (see PodOps.QuarantinePodByIP).
//
// Why egress-deny-on-attacker rather than ingress-allow-except-on-targets:
// Kubernetes NetworkPolicies are ADDITIVE — a connection is permitted if ANY
// policy selecting the pod allows it. An "ingress allow 0.0.0.0/0 except
// attacker" is therefore silently defeated by any broader allow policy on the
// same target pods (e.g. a previous incident's quarantine). Restricting the
// attacker Pod's own egress cannot be overridden by ingress policies and stops
// the port-scan / lateral movement at the source. Reversible by deleting the
// NetworkPolicy and removing the label.
package response

import (
	"fmt"
	"strings"
	"time"
)

// DefaultQuarantineNamespace is where the attacker Pod is expected to live and
// where the NetworkPolicy is created (matches the incident-service RBAC scope).
const DefaultQuarantineNamespace = "zt-targets"

// QuarantineRequest describes a NetworkPolicy draft request.
type QuarantineRequest struct {
	IncidentID int64
	SourceIP   string
	Namespace  string // ns of the attacker pod; defaults to DefaultQuarantineNamespace
	Severity   string
	Reason     string
}

// GenerateQuarantine returns NetworkPolicy YAML that denies all egress from the
// attacker Pod, which is selected via the per-incident label LabelKey(id)=true.
// The enforcer (PodOps.QuarantinePodByIP) applies that label to the Pod whose
// IP matches the incident source at enforcement time.
//
// On a NetworkPolicy-aware CNI (Calico, Cilium) this drops the attacker's
// outbound connections at its node. On a CNI without policy enforcement
// (Flannel) it has no effect — see docs/cni-migration-runbook.md.
func GenerateQuarantine(req QuarantineRequest) string {
	ns := req.Namespace
	if ns == "" {
		ns = DefaultQuarantineNamespace
	}
	srcIP := req.SourceIP
	if srcIP == "" {
		srcIP = "0.0.0.0" // safe-default; Apply will reject via validation
	}
	name := fmt.Sprintf("zt-quarantine-incident-%d", req.IncidentID)
	label := LabelKey(req.IncidentID)

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by zt-soc/incident-service at %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "# Incident: %d  source: %s  severity: %s\n", req.IncidentID, srcIP, req.Severity)
	fmt.Fprintf(&b, "# Reason: %s\n", req.Reason)
	fmt.Fprintln(&b, "#")
	fmt.Fprintf(&b, "# Effect: denies ALL egress from the attacker Pod (IP %s, label %s=true)\n", srcIP, label)
	fmt.Fprintf(&b, "# in namespace %q. Reversible by `kubectl delete -n %s networkpolicy %s`.\n", ns, ns, name)
	fmt.Fprintln(&b, "apiVersion: networking.k8s.io/v1")
	fmt.Fprintln(&b, "kind: NetworkPolicy")
	fmt.Fprintln(&b, "metadata:")
	fmt.Fprintf(&b, "  name: %s\n", name)
	fmt.Fprintf(&b, "  namespace: %s\n", ns)
	fmt.Fprintln(&b, "  labels:")
	fmt.Fprintln(&b, "    app.kubernetes.io/managed-by: zt-soc")
	fmt.Fprintf(&b, "    zt-soc/incident-id: \"%d\"\n", req.IncidentID)
	fmt.Fprintln(&b, "spec:")
	fmt.Fprintln(&b, "  podSelector:")
	fmt.Fprintln(&b, "    matchLabels:")
	fmt.Fprintf(&b, "      %s: \"true\"        # the offending pod, labelled by the enforcer\n", label)
	fmt.Fprintln(&b, "  policyTypes: [Egress]")
	fmt.Fprintln(&b, "  egress: []                    # deny ALL egress from the quarantined pod")
	return b.String()
}

// LabelKey is the per-incident marker label applied to the offending Pod so the
// egress-deny NetworkPolicy can select it.
func LabelKey(incidentID int64) string {
	return fmt.Sprintf("zt-soc-quarantine-%d", incidentID)
}
